### ISSUE TITLE
Setup cron jobs

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#109]
```
@daily php /path/to/your/wiki/extensions/LocalisationUpdate/update.php --quiet
```

https://www.mediawiki.org/wiki/Extension:LocalisationUpdate

**Comment by traumschule** [comment]
[done](https://github.com/traumschule/hitchwiki/blob/ansible/scripts/ansible/roles/hitchwiki/tasks/mediawiki.yml)
