### ISSUE TITLE
Fix SetupUser script

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#113]
It outputs:
```
==> default: Setup CheckUser...
==> default: Could not open input file: install.php
```

when doing `vagrant up` first time.

See `./scripts/bootstrap_vagrant.sh`

**Comment by omelnyk** [comment]
https://www.mediawiki.org/wiki/Extension:CheckUser#On_an_existing_wiki:

> navigate to the extensions/CheckUser folder and run php install.php. Ensure that you are running a PHP version 5.x install, otherwise this script will not run. If install.php is not present then run php maintenance/update.php again

We're already doing `maintenance/update.php` several lines above, and the extension's tables are in place on beta.
