### ISSUE TITLE
Editing articles with VisualEditor gives 404 error

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#118]
Related https://www.mediawiki.org/wiki/Topic:Sz4ld1giul6g7igp ?

**Comment by simison** [comment]
Check also settings from `/etc/mediawiki/parsoid/config.yaml`

**Comment by omelnyk** [comment]
Fixed by 95618445105bf2abee172a1db9fce50b503ab27f

Included wrong issue number in commit by mistake.
