### ISSUE TITLE
Disable map for language versions

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#119]
We'll have the map and semantic stuff for `en` version only for now, until we'll figure how to handle languages. For now it complicates things too much and it's better to do initial testing in one language version only before using it for everything.

**Comment by omelnyk** [comment]
I tried to narrow down the milestone to concentrate on what absolutely has to be done before we announce the public beta this week, to make sure we at least reach that phase.

**Comment by simison** [comment]
kk

**Comment by simison** [comment]
FYI @pmgouveia
