### ISSUE TITLE
[migrate] Upgrade to MediaWiki 1.28 on hitchwiki.org

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#120]
It needs to be done before we generate a database dump provided to the migration script.

Although we used an old dump on beta.hitchwiki.org and it _kind of_ works, [MediaWiki documentation](https://www.mediawiki.org/wiki/Manual:Moving_a_wiki#Versions_and_upgrading) strongly advises against doing that:
> You should only move a database into another MediaWiki installation if they both run the same MediaWiki version.

**Comment by guaka** [comment]
Still relevant?

**Comment by simison** [comment]
@guaka yep!

We didn't get to it yet.

**Comment by traumschule** [comment]
looks good to me: [MediaWiki | 1.28.1](http://hitchwiki.org/en/Special:Version)

Thanks!
