### ISSUE TITLE
Think about spot names

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#125]
Now `Municipality, Country (lat, lon)`

Could be just `spot-123`

**Comment by omelnyk** [comment]
In the migration script, I'm using eg. `Spot 123`, where 123 is the spot id in the old database.

But this scheme isn't easy to replicate for the new spots, because:
- not possible to know the page_id before it gets saved.
- old spot id != new page_id

**Comment by simison** [comment]
It's probably possible to hook to it on pre save, get latest page id+1 and
store that instead of whatever else that is sent to the API.
