### ISSUE TITLE
https

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#127]
- [ ] Ensure Geonames calls works (either replace with MapBox geocoder or route via server) ([e.g. here](https://github.com/Hitchwiki/HWMap-extension/search?utf8=%E2%9C%93&q=api.geonames.org))
- [ ] Install [Let's Encrypt](https://letsencrypt.org/) bot
- [ ] Run cert updates via cron

**Comment by omelnyk** [comment]
It's also important for our future mobile apps: https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/

**Comment by pmgouveia** [comment]
I'm using this repo:
https://github.com/letsencrypt/letsencrypt

to install the cert only need to run:
`$ ./certbot-auto --apache -d ${DOMAIN} -d www.${DOMAIN} --no-self-upgrade`

to auto-update just run a cronjob with:
` $ /scripts/letsencrypt/certbot-auto renew --quiet --no-self-upgrade`
