### ISSUE TITLE
Organize edit camp in Berlin

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#136]
Next spring/summer?

Introduce people to:
- wiki markup
- GitHub issues

Mass-edit:
- "Hitching out" on city pages --> spots
- table rows on [road pages](http://hitchwiki.org/en/A1_(Netherlands)) --> spots? then how do we make these spots show up on road pages?
- assign/unassign spots from cities, where migration script got it wrong 
- merge duplicate spots

Need to develop tools that facilitate the above

**Comment by traumschule** [comment]
@slacle and me want to meet in Berlin at the end of this month to test frontend development with vagrant. The roadmap could get an update and some issues probably need a new milestone:
- open tickets from [Vilnius hackathon](https://github.com/Hitchwiki/hitchwiki/milestones/Hackathon%20VLN%2012/2016) (10)
- [Berlin](https://github.com/Hitchwiki/hitchwiki/milestone/5) (3)
- v2 setup beta.hitchwiki.org with ansible and migrate content
- [v3 production ready](https://github.com/Hitchwiki/hitchwiki/milestones/Hitchwiki%20v3%20production%20ready)
- [future](https://github.com/Hitchwiki/hitchwiki/milestones/Future)

I propose to dedicate the [migration issues](https://github.com/Hitchwiki/hitchwiki/labels/migrate) (#167) a new milestone (v2) or assign them to [Berlin](https://github.com/Hitchwiki/hitchwiki/milestone/5). When current hitchwiki.org is v1 and the new  will be v3, what's v2? Was it just never released or did you have other plans?
