### ISSUE TITLE
Get rid of Maps extension

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#139]
[Extension:Maps' #coordinates parser function](https://www.semantic-mediawiki.org/wiki/Extension:Maps/Coordinates#Formatting_coordinates):

```{{#coordinates:primary|lat|lng}}```

 conflicts with [Extension:GeoData's #coordinates function](https://www.mediawiki.org/wiki/Extension:GeoData#Examples):

```{{#coordinates:lat,lng}}```

We're resorting to a [dirty hack](https://github.com/Hitchwiki/hitchwiki/blob/b16c8e82f46d8776d0beb693565675156ad1a77a/scripts/server_install.sh#L133-L144) to disable the former.

But do we need Maps extension at all? Which of its features are we dependent on?

**Comment by traumschule** [comment]
Is this the reason why the map tag (`<map`) is not parsed in the wiki? Would be great to have it enabled again.

**Comment by simison** [comment]
@traumschule nah, this issues is regarding new unpublished version which is due for a long time already.

`<map>` in old version is broken just because custom plugin we wrote for got outdated trough several MediaWiki updates. Someone just would need to rewrite it, but it's not really worth the effort at this point.

**Comment by simison** [comment]
@omelnyk do you remember if you opened an issue at any of those extensions repositories for this?

**Comment by traumschule** [comment]
ok, no problem. Let me have a look at the code.

**Comment by traumschule** [comment]
The feature "Maps on article pages" was the reason I got involved with HW development. Is this already implement? I did not manage to see it live yet.

**Comment by simison** [comment]
@traumschule yep, it's implemented. The map should appear on pages which are created via city or country forms. Something might be broken though, you might want to check if you can see errors at browser console.

**Comment by traumschule** [comment]
just tried it with w3m on beta directly:

> [81d07c510d298dc48048de0d] [no req] Error from line 1626 of /var/www/public/wiki/extensions/PageForms/includes/PF_FormPrinter.php: Class '\HWLI\HWLocationInput::init'
> not found
> 
> Backtrace:
> 
> #0 /var/www/public/wiki/extensions/PageForms/includes/PF_FormPrinter.php(1127): PFFormPrinter->formFieldHTML(PFFormField, NULL)
> #1 /var/www/public/wiki/extensions/PageForms/includes/PF_AutoeditAPI.php(934): PFFormPrinter->formHTML(string, boolean, boolean, integer, string, string, NULL)
> #2 /var/www/public/wiki/extensions/PageForms/includes/PF_AutoeditAPI.php(115): PFAutoeditAPI->doAction()
> #3 /var/www/public/wiki/extensions/PageForms/specials/PF_FormEdit.php(92): PFAutoeditAPI->execute()
> #4 /var/www/public/wiki/extensions/PageForms/specials/PF_FormEdit.php(43): PFFormEdit->printForm(string, string, NULL)
> #5 /var/www/public/wiki/includes/specialpage/SpecialPage.php(522): PFFormEdit->execute(string)
> #6 /var/www/public/wiki/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(string)
> #7 /var/www/public/wiki/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
> #8 /var/www/public/wiki/includes/MediaWiki.php(862): MediaWiki->performRequest()
> #9 /var/www/public/wiki/includes/MediaWiki.php(523): MediaWiki->main()
> #10 /var/www/public/wiki/index.php(43): MediaWiki->run()
> #11 {main}
> 
> Retrieved from "http://hitchwiki.test/en/Special:FormEdit/City/Berlin"
