### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#141]
most are fine, but not always:
- http://beta.hitchwiki.org/en/File:Carl_Nai_Maroc.jpg
- http://beta.hitchwiki.org/en/File:IMG_5392.JPG#/media/File:IMG_5392.JPG

**Comment by simison** [comment]
These are from some age-old server crash (3-5 years ago). Backups were partial and thus we lost a few images.

Can't be helped; only todo would be to remove img tags for missing images, but that can be done manually.
