### ISSUE TITLE
production setup

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#142]
For now:
- [ ] shortlist apt package dependencies
- [ ] add "production setup" steps to readme

For future:
- Ansible? Puppet?

**Comment by simison** [comment]
@chmac do I remember wrong or did you in Huelva suggest some easier/smarter tool for scripting the server setup?

**Comment by chmac** [comment]
Ansible is the new shit these days. Much simpler architecture, "easier to reason about" as is the buzzword these days. :-)

**Comment by traumschule** [comment]
please test the [ansible branch](https://github.com/traumschule/hitchwiki/tree/ansible) and let me know of any errors
