### ISSUE TITLE
Category:Generic

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#145]
Auto-assign Category:Generic to all pages that aren't covering a specific location (don't contain a Spot/Area/City/Country template).

Is it even possible without using a bot?

**Comment by simison** [comment]
Humm, why?

**Comment by traumschule** [comment]
Just checked: There are hundreds of [pages without category](http://hitchwiki.org/en/index.php?title=Special:UncategorizedPages&limit=500&offset=0). Having a "Generic" tag on them wouldn't help much.
