### ISSUE TITLE
Mapbox vendor lock-in

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#148]
@simison, can we obtain our customized map tiles all at once from Mapbox and use them freely? Are there any major obstacles preventing us from self-hosting them, if the need arises?

**Comment by simison** [comment]
@omelnyk we can switch to any other tile provider easily, no prob. Thus it's not a vendor-lock. Indeed there's already OSM default map layers in there.

Just the problem with the most of the free tile providers is that they don't have https for free or/and their styles suck (OSM especially).

**Comment by simison** [comment]
I actually already added backup OSM layer now to both [HWMap-extension](https://github.com/Hitchwiki/HWMap-extension) and [HWLocationInput-extension](https://github.com/Hitchwiki/HWLocationInput-extension). Basic OSM streets layer comes up when any of the Mapbox config fields ([from settings.ini](https://github.com/Hitchwiki/hitchwiki/blob/master/configs/settings-example.ini#L65-L69)) is empty.

The problem pretty much any free alternatives to MapBox tiles is that they don't support https.

So it's good to keep door open away from MapBox (esp. for development), but use it nevertheless.

**Comment by simison** [comment]
I was testing https locally (you can now install the whole setup with self signed https), see the readme.

I figured that OSM tile-server I was using at Hitchwiki (`//{s}.tile.osm.org/{z}/{x}/{y}.png`) doesn't work with https but `//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` works. So even less of a vendor lock anymore. We can keep beautiful MapBox tiles and have this easy switch to OSM available.
