### ISSUE TITLE
Printed book

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#150]
Noah [wrote](https://www.facebook.com/groups/hitchgathering/permalink/1560315453982015/) on Facebook:

> I had the idea to convert the major articles of the hitchwiki into a book.
>
> Purpose: 
> * Print it at online printing service and put it on your shelf for home research or to get ideas where to go and show friendsand also for fun.
> * Use as regular updated eBook on your e-reader/phone for offline-areas/countries.
> * I think the Hitchwiki is an awesome cultural document that should be available offline.
> * Because Hitchwiki is awesome.
>
> I have no clue if that idea reasonates in our group so please give me some thumbs up or thumbs down to see if there are any interested people. 
> Also, I need some people (maybe from #Hitchwiki) to help me with 
> * sort the articles by geografical and alphabetic order and decide which ones we can dismiss
> * converting mediawiki syntax to latex
> * create an awesome latex style for the book
> * help automating the thing as an algorythm so you can get your updated book without any problems at any time

Printed book idea has been already brought up at HitchGatherings a few times, so there is definitely an interest for that.

**Comment by omelnyk** [comment]
Noah mentioned that he wants to use LaTeX.

Research possible options:
- [Collection extension](https://www.mediawiki.org/wiki/Extension:Collection) that's used by  Wikipedia for [book generation](https://en.wikipedia.org/wiki/Special:Book) (does it support LaTeX output?)
- using [Parsoid](https://www.mediawiki.org/wiki/Parsoid) directly (does it support LaTeX output)?
- using [Wiki2LaTeX extension](https://www.mediawiki.org/wiki/Extension:Wiki2LaTeX)
- using a client-side library for wikitext-latex conversion in conjunction with [pywikibot](https://www.mediawiki.org/wiki/Manual:Pywikibot) (we're already [using pywikibot for migration](/Hitchwiki/hitchwiki/tree/master/scripts/bot/migrate)

**Comment by simison** [comment]
I don't think he took on this. ;-)
