### ISSUE TITLE
upgrade beta.hitchwiki nightly 

### ISSUE THREAD

**Issue by pmgouveia** [Hitchwiki/hitchwiki#155]
so that beta testers can start giving feedback! :)

**Comment by traumschule** [comment]
building up on your great work the [ansible](https://github.com/traumschule/hitchwiki/tree/ansible) branch is nearly production ready

**Comment by traumschule** [comment]
Travis CI can run (daily) cron jobs or [deploy](https://docs.travis-ci.com/user/deployment/script/) after successful builds. I prefer triggered deployment on new commits rather than chronological.

**Comment by simison** [comment]
It's alright to do this stuff manually. ;-)
