### ISSUE TITLE
Login has been canceled as a precaution for hijacking

### ISSUE THREAD

**Issue by leocarona** [Hitchwiki/hitchwiki#161]
>"There seems to be a problem with the login session; this action has been canceled as a precaution against session hijacking. Go back to the previous page, reload that page and then try again."
>Made registration through Chrome. This problem appears at Opera"

"It just happen on Opera. On Chrome everything worked"

* reported by [Augustas Verbickas](https://github.com/AugustasV) find him on Hitchwiki FB inbox messages

**Comment by simison** [comment]
Yup, not sure what would fix this from our end but at user's end clearing cookies typically helps.

**Comment by simison** [comment]
@guaka the session folder fix didn't completely nail it, I can still see the error. I tried to remove the line from config but it won't help.

Doing some more searching on this.

**Comment by simison** [comment]
@guaka so I added `$wgCookiePrefix = "hw_";` to config and saw the issue go away for myself. Let's see if we get messages about this again.

**Comment by simison** [comment]
Got confirmation from someone who reported the bug earlier. Closing for now.
