### ISSUE TITLE
replace settings.ini by settings.yml

### ISSUE THREAD

**Issue by traumschule** [Hitchwiki/hitchwiki#166]
For ansible (#164) variables are stored in `configs/settings.yml` which is a copy of `settings.ini`. Over time latter won't be necessary anymore. Currently following files depend on it:

# migration bot
load `settings.yml` with [PyYAML](http://pyyaml.org/wiki/PyYAMLDocumentation) for #167

## settings.ini

scripts/bot/migrate/spotmigrate.py:settings.read('../../configs/settings.ini')
scripts/bot/migrate/extramigrate.py:settings.read('../../configs/settings.ini')
scripts/bot/migrate/articlemigrate.py:settings.read('../../configs/settings.ini')
scripts/bot/migrate/articlemigrate.py:# list definition in settings.ini
scripts/bot/migrate/articlemigrate.py:$hwConfig = parse_ini_file("../../configs/settings.ini", true);

## _settings.sh

- scripts/export_db.sh:source "$SCRIPTDIR/_settings.sh"
- scripts/bot/bot_install.sh:source "$SCRIPTDIR/_settings.sh"
- scripts/migrate.sh:source "$SCRIPTDIR/_settings.sh"

## _path_resolve.sh

- scripts/import_pages.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/import_pages.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/resinstall.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/export_pages.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/import_interwiki.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/cert_selfsigned.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/update.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/migrate.sh:source "scripts/_path_resolve.sh"
- scripts/vagrant/permissions.sh:source "scripts/_path_resolve.sh"
- scripts/export_pages.sh:source "scripts/_path_resolve.sh"
- scripts/export_db.sh:source "scripts/_path_resolve.sh"
- scripts/run_mw_jobs.sh:source "scripts/_path_resolve.sh"
- scripts/bot/bot_install.sh:source "scripts/_path_resolve.sh"
- scripts/migrate.sh:source "scripts/_path_resolve.sh"

# DONE

Mediawiki now [loads settings.yml](https://github.com/Hitchwiki/hitchwiki/pull/164#pullrequestreview-71045789)
- mediawiki.php
- public/robots.txt.php

These scripts are already replaces by ansible
     - configs/settings-example.ini
     - scripts/server_install.sh
     - scripts/install_funcs.sh
     - scripts/install_parsoid.sh
     - scripts/create_users.sh
     - scripts/install_local.sh
     - scripts/vendor/bash_ini_parse
     - scripts/cert_selfsigned.sh

**Comment by traumschule** [comment]
scripts/cert_selfsigned.sh is now in ansible: ed4f069bb42a210b312fb5b217d7b8fa2ece4ed9

**Comment by simison** [comment]
Just wanted to clarify here that there's no need to:
- write Ansible scripts for the migration bot
- there's no need to rewrite migration bot read yml configs: we can manually go around that since the bot is going to be used just once and then removed completely.

**Comment by guaka** [comment]
see #186
