### ISSUE TITLE
Make it possible to have different types of spots?

### ISSUE THREAD

**Issue by leocarona** [Hitchwiki/hitchwiki#168]
It would be nice if the Hitchwiki app, MyHitchhikingSpots for Android, eventually starts syncing all hitchhiking spots (with waiting times, etc) added by the users to Hitchwiki. But besides hitchhiking spots, the app also allows the users to save other locations that she/he wants to remember, as well as the final destination of each hitchhiking trip.

### Possible solution
To avoid the need of keeping a separate webservice/database, should we then add new attributes to the spots to include these differences? On the app, we have columns such as _IsHitchhikingSpot_, _IsWaitingForARide_, _IsPartOfARoute_, _IsDestination_, _AttemptResult_, and a few more that can be checked [**here**](https://github.com/Hitchwiki/MyHitchhikingSpots-for-Android/blob/master/app/src/main/java/com/myhitchhikingspots/model/Spot.java).

Impact: probably all the existing queries that Hitchwiki has nowadays should be updated to include some new conditions to their **WHERE** clause.

------

I'd love to hear what you guys would say about this. Should we not care about this now, maybe? Any other ideas on how to make the synchronisation between the app and Hitchwiki possible? There might be a lot of new spots been added by people through the app, it can help our databases grow. We can keep in mind that MyHitchhikingSpots is a Hitchwiki app and maybe we can do more to make it feel like it. 

PS) Sorry if I'm adding this topic in the wrong place. Please, redirect me to a proper place to discuss this if there's any.

**Comment by leocarona** [comment]
Actually it might be more than 2 columns. On the app, every spot is an "attempt to get a ride". If the user gets a ride, we have a column called _attempt_result_ that will be set to something like "got a ride". If he gives up on hitchhiking at that location (because he decided to try another spot, because he decided to sleep overnight somewhere nearby and try again in the next day, etc), _attempt_result_ will be set to something like "took a break". 

Anyways, this topic here is mostly to discuss if we should start considering a solution to allow MyHitchhikingSpots app to sync the hitchhiking spots added by users to Hitchwiki databases, and if so, we can discuss how to do it. [**Here**](https://github.com/Hitchwiki/MyHitchhikingSpots-for-Android/blob/master/app/src/main/java/com/myhitchhikingspots/model/Spot.java) you can check all attributes that we store for each spot added by users through the app.

**Comment by traumschule** [comment]
thinking in mediawiki logic routes have a `name`, `tag`, `start_date`, `end_date`. they can be defined with a template on a user page. when a user adds a spot with a matching `tag` or `date` with an app (text snippets appended to the page), the software shows them as as a trip, maybe blog entries on the left and a map with POIs on the right. Would that be similar to what you had in mind?

**Comment by leocarona** [comment]
Hnn, I've been focused on the app development so I'm not much familiar with MW tech terms. Would you try to explain that to a dumb person, maybe? :)

I've just edited my post also trying to make it a bit more complete and possibly easier to be understood - could you please see if the solution you thought of can also be used considering the other columns mentioned now?

**Comment by traumschule** [comment]
TBH the app is not my wokring field and I need to read into the code first. So I'll leave some space for others to comment here :)

**Comment by simison** [comment]
>IsHitchhikingSpot, IsWaitingForARide, IsPartOfARoute, IsDestination, AttemptResult

It probably won't make sense to complicate the setup now at this point. There might be some types of spots that make sense adding in different type (gas stations, gas stations with cross-over?), but first we just need to get the thing out.

It probably won't make sense to mix main spots table with private temporary content relevant to only one user; it will just bloat it up and make it slower to query.

In far future when this is rolling smoothly in HW, it might make sense to deploy the same software for Trashwiki and Nomadwiki. Especially Nomadwiki could do with all sorts of other spots: good wild camping beaches, abandoned buildings, good parks for camping, free water sources etc etc

If you can find a clean way to store it under `/User:Username` -namespace, that probably wouldn't hurt, but not that everyone can read+write to those pages so they're not really private.

**Comment by leocarona** [comment]
Good points. I'll try and think in other possible solutions. 

Does MW restrict developers from adding new customised tables to the database? 
How does it sound for you guys if we add a table containing these additional fields? 

That way I think we can store data that is private for MyHitchhikingSpots users in a new table and this way it shouldn't affect the speed of the current existing queries. 

Please notice that the main goal of the app is to get users to save spots that will be public for everyone using Hitchwiki one day. The options of adding additional private spots is mostly to make the app more useful for yourself if you need to save some other types of spots on your way (gas station, police stations, speed bumps, radars, a place where the driver stopped to take a pee and you saw something nice, etc). We could also consider using these spots of other types saved through the app as public HW data if/when HW begins to give options to add other types of spots one day.

I also agree that there's a lot more urgent stuff that need to get more focus right now on HW, so nobody should need to start working on what we're discussing here any soon. It might be just a good idea to discuss the possible solution for this right now so that I can have some perspective about the future of the app and its option to sync data to HW, which is an option awaited by many HW users using the app.

**Comment by traumschule** [comment]
A new table would make sense, although it's a lot work to maintain it. MW templates are the easiest solution, IMHO. Possible workflow:
1. http://beta.hitchwiki.org/en/Special:HWMap#hwmap-add (login: hitchwiki/autobahn)
2. zoom to a spot, click 'continue' (currently broken #173)
3a. public spots can be added to a page (of a user or some city/country) via [form](http://nomadwiki.org/en/Nomadwiki.org:Admin#Forms_and_categories) with a [template](http://nomadwiki.org/en/Template:Location):
```
{{Spot
|lat=
|lng=
|desc=
|IsHitchhikingSpot=
|IsWaitingForARide=
|IsPartOfARoute=
|IsDestination=
|AttemptResult=
}}
```
(The variable names are suboptimal, for example if it a sport is part of a route, you could set `route=ROUTE_ID|ROUTE_NAME` or leave it empty.)

3b. a form with a 'private' checkbox can be set -> the spot is written to the user page (encrypted with gpg or similar), hidden in a comment
4b. when the user page is viewed decryption only happens when the user is logged in ...
(The private option does not really make sense, is complicated to setup and nd I can't see why private spots should be in HW)

If it's not written to a wiki page, how would it be related to HW? Then it is more like a independent application, i guess.

**Comment by leocarona** [comment]
Thanks, I'll have a look about MW templates option.

About the option of private spots,
The idea is that the app should be useful for the user while hitchhiking, to encourage them to save their hitchhiking spots and possibly sharing them publicly to others. Besides MHS, people were having to use a second app (like Maps.Me, Google Maps, etc) in parallel because once in a while they found themselves willing to save a non-hitchhiking location to remind later. Non-hitchhiking locations could be the user's destination (needed to draw the start and end of a hitchhiking route on the map); could be a gas station; could be a better location that the user saw from inside of a car where he felt like he should try to hitchhike at in a next time; etc. These non-hitchhiking locations wouldn't be useful for other users, but they might turn the app a bit more useful.

Other than that, users might not feel comfortable in using the app if every information they save on it is publicly shared. I think it can be nice and necessary for users to opt-out, to select which spots they want public and which ones they want private. 

Maybe it would help if you tried the app while hitchhiking one day, if you're an Android user. It might be easier to see the need of private spots, I think. 

It's ok if nobody on the development team sees the need for this option, but then I might need to build/find a separate web-service to store the private information, while only the public ones can be uploaded to HW.

**Comment by leocarona** [comment]
I have just edited my last answer here.

But again about the private spots, it's important to keep in mind that HW website let's user saves hitchhiking spots that are not connected anyhow to each other. Whereas mobile app would probably be expected by everyone to organise their hitchhiking spots as separate routes, a part of also letting them save spots where they've hitchhiked which don't belong to any route. 

These options make the app more useful for the users, but again, to be able to draw a hitchhiking route from start to end, we need to know where's the end. The end is a non-hitchhiking spot that is necessary to know, but it should be private as alone it's not useful for other hitchhikers in any way.

With these long texts I'm trying to explain the need of expanding HW to accept non-hitchhiking spots and to also support saving data that is not public to everyone. 

Everyone reading this discussion who are interested in the question, please feel free to collaborate with ideas/questions/whatever. The goal is to move this project together, even if I'm alone on MHS development currently. ;-)

**Comment by traumschule** [comment]
what about adding non hitchhiking spots to nomadwiki.org and referencing them with the android app?

**Comment by leocarona** [comment]
I guess this issue will be fixed by the new issues some of us agreed about (link below). Therefore I'm closing this current issue as discussion may be continued on the most recent one.

https://github.com/Hitchwiki/hitchwiki-private/issues/169
