### ISSUE TITLE
Mouse events don't reach map layer

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#169]
It's not possible to interact with the map right now. Probably just some changes at MW DOM via version updates.

https://beta.hitchwiki.org/en/Special:HWMap

This one covers the whole map element currently: `.page-Special_HWMap .mw-indicators.mw-body-content` — hiding it helped. Hit this to browser console to test:
```js
jQuery('.page-Special_HWMap .mw-indicators.mw-body-content').hide()
```

This might also cause issues:
```
.page-Special_HWMap .mw-body-content {
  pointer-events: none;
}
```

**Comment by traumschule** [comment]
The map disappears completely when I 
1. add to `.page-Special_HWMap` in  `extensions/HWMap/modules/less/specialpage.less`
- `mw-indicators.mw-body-content.hide()`
2. add to `.mw-body-content` in  `extensions/HWMap/modules/less/specialpage.less`
- `display: none;`
