### ISSUE TITLE
weekly db dumps available to public

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#17]
http://hitchwiki.org/dumps/

**Comment by guaka** [comment]
today (Jan 2015) it still has dumps from  04-Sep-2013

![screen shot 2015-01-14 at 10 56 19](https://cloud.githubusercontent.com/assets/54728/5736930/00101a4a-9bdc-11e4-844c-61b226a088d2.png)

**Comment by simison** [comment]
@omelnyk wanna set this up for the new HW?

**Comment by traumschule** [comment]
dumps are fixed for the wiki: http://hitchwiki.org/en/Hitchwiki:Database_dumps

**Comment by guaka** [comment]
seems to work
