### ISSUE TITLE
Search header visually broken

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#170]
![image](https://user-images.githubusercontent.com/87168/32135181-75dd6184-bc03-11e7-9e1a-6b73ffa16e52.png)

**Comment by traumschule** [comment]
this might have been temporary, current [beta](https://beta.hitchwiki.org/en/Main_Page) looks clean to me

**Comment by traumschule** [comment]
It reappeared yesterday, the upgrade to mediawiki 1.29.2 could be related.
![hw_searchbar](https://user-images.githubusercontent.com/31551045/32989230-2c733a4c-cd0a-11e7-9fde-195c4e12d45a.png)
The height of the search bar is defined in `hw-mediawiki-extensions/HitchwikiVector-extension/resources/styles/ext.HitchwikiVector.less`
```
#p-search #simpleSearch {
    height: 48px;
}
```
`height: 30px` might be a better value.
