### ISSUE TITLE
Ansible intro, wishlist and bugs

### ISSUE THREAD

**Issue by traumschule** [Hitchwiki/hitchwiki#172]
[Since November 2017](https://github.com/Hitchwiki/hitchwiki/issues/164) we use [ansible](https://github.com/ansible/ansible) to test and deploy Hitchwiki. It can provision a local vagrant box or deploy to a remote server. Feel free to subscribe and add reports related to our ansible playbooks!

- HW master: [![Build Status](https://travis-ci.org/Hitchwiki/hitchwiki.svg?branch=master)](https://travis-ci.org/Hitchwiki/hitchwiki)
- master: [![Build Status](https://travis-ci.org/traumschule/hitchwiki.svg?branch=master)](https://travis-ci.org/traumschule/hitchwiki)
- ansible: [![Build Status](https://travis-ci.org/traumschule/hitchwiki.svg?branch=ansible)](https://travis-ci.org/traumschule/hitchwiki)
- testing: [![Build Status](https://travis-ci.org/traumschule/hitchwiki.svg?branch=testing)](https://travis-ci.org/traumschule/hitchwiki)

# Test it!
```
git clone https://github.com/traumschule/hitchwiki -b testing
./scripts/vagrant/install.sh
./scripts/deploy_remote.sh HOST
```
For details see [INSTALL.md](https://github.com/traumschule/hitchwiki/blob/ansible/INSTALL.md) and [ansible/README.md](https://github.com/traumschule/hitchwiki/blob/ansible/scripts/ansible/README.md).

See it live on [beta.hitchwiki.org](https://beta.hitchwiki.org) (experimental: `6pna4byhdcdyprdc.onion`)

# Workflow
_feature -> testing -> ansible -> HW master -> production_
- feature branches should rebase testing, if test with travis and vagrant succeed, they are merged
- testing: runs CI build tests for added latest features (test latest features and make sure all methods install before merging into ansible)
- ansible: to be run with vagrant (development)
- master: (to be) synced with current HW master branch
- beta: `beta.hitchwiki.org`is deployed from testing or ansible branch
- production: `hitchwiki.org` has it's own repository and is updated after some time when beta looks stable enough

## To be merged into [ansible](https://github.com/traumschule/hitchwiki/tree/ansible) branch
- [X] _branch:torhs_ set up a [tor hidden service](https://blog.torproject.org/tors-fall-harvest-next-generation-onion-services) ([why](https://blog.torproject.org/facebook-hidden-services-and-https-certs)? [facebook](https://facebookcorewwwi.onion/) and [NYT](https://www.nytimes3xbfgragh.onion) offer it, so we should too)
  - [hidden service v2](https://www.torproject.org/docs/tor-hidden-service.html.en): `6pna4byhdcdyprdc.onion`
  - [hidden service v3](https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Howtosetupyourownprop224service): `ncwpcjalalxyxj2247b6ts45dsqlt6ihi5dmb6uuv5c5e45pkfgxm6qd.onion` (needs [TBB 7.5.x](https://blog.torproject.org/tor-browser-75a8-released))
  - [-] ~MW ignores the requested url and rewrites it to `beta.hitchwiki.org`. To preserve the .onion address a [proxy](https://meta.wikimedia.org/wiki/Grants:IdeaLab/A_Tor_Onion_Service_for_Wikipedia#What_software_do_we_need.3F) is necessary~ $wgServer is commented out now because it is [detected automatically](https://www.mediawiki.org/wiki/Manual:$wgServer#Autodetection)
- [X] turn off logging of IP addresses in apache (removeip module)
- [X] add [vagrant-cachier](http://fgrehm.viewdocs.io/vagrant-cachier/)

## In progress
Tasks for [HWv3](https://github.com/Hitchwiki/hitchwiki/milestone/4): [project roadmap](https://github.com/Hitchwiki/hitchwiki/projects/1), upcoming: #136 HW gathering in Berlin

_development is currently stalled because of a [bug in vagrant](https://github.com/hashicorp/vagrant/issues/9220)_

## Would be nice
- [ ] re-enable maildev
  - [ ] status.sh: check why [maildev and monit are not configured in docker](https://travis-ci.org/traumschule/hitchwiki#L1362) and the started test for maildev and phpmyadmin fail
- [ ] :rocket: speed up installation 
  - [ ] use [docker compose to create a HW image](https://github.com/albjeremias/hitchwiki/commit/0e45e5959da8ce54ed0b27d2ecebdf8bd62bd03b)
  - [ ] run jobs in parallell
  - [ ] apply [perfomance tuning tipps](http://nomadwiki.org/w/index.php?title=Valencia&diff=next&oldid=6337)
  - [ ] [optimize downloads](https://www.ansible.com/blog/ansible-performance-tuning) (caching)
- [ ] setup [discourse](https://github.com/discourse/discourse/blob/master/docs/DEVELOPER-ADVANCED.md) with [foreman](https://docs.ansible.com/ansible/latest/foreman_module.html) - see `scripts/ansible/roles/discourse/tasks/main.yml`
- [ ] run `rgrep 'TODO' scripts/ configs/`to check the code for TODOs
- [ ] #132 disable beta menus for prod
- [ ] test MW [1.30](https://phabricator.wikimedia.org/source/mediawiki/browse/REL1_30/RELEASE-NOTES-1.30) ([tar](https://releases.wikimedia.org/mediawiki/1.30/mediawiki-1.30.0-rc.0.tar.gz), [.sig](https://releases.wikimedia.org/mediawiki/1.30/mediawiki-1.30.0-rc.0.tar.gz.sig)): [upgrade](https://www.mediawiki.org/wiki/Manual:Upgrading)
- [ ] apache configs for each domain (currently we have domain and domain2 in settings. if both are set it could make sense, to create separate apache config files with vhosts for port 80 and 443)
  - restructuring the domain variable(s) affects following files:
> scripts/configs/settings-example.yaml
> scripts/configs/parsoid_config.yaml
> scripts/ansible/roles/discourse/tasks/main.yml
> scripts/ansible/roles/hitchwiki/tasks/domain.yml
> scripts/ansible/roles/hitchwiki/tasks/mediawiki.yml
> scripts/ansible/roles/hitchwiki/tasks/dev.yml
> scripts/ansible/roles/hitchwiki/tasks/tls.yml
> scripts/ansible/roles/hitchwiki/tasks/letsencrypt.yml
> scripts/ansible/roles/hitchwiki/tasks/tls_selfsigned.yml
> scripts/ansible/roles/status/tasks/main.yml
- [ ] HW dump import
- [ ] honor `dev: beta` as a pre-step towards production with TLS and maildev enabled

## Security and stability
- [ ] use [ssh jail](https://github.com/geerlingguy/ansible-role-ssh-chroot-jail) for deployment via travis
- [ ] check why [secure db settings for production](https://github.com/traumschule/hitchwiki/blob/ansible/scripts/ansible/roles/hitchwiki/tasks/production.yml) lock us out of the dbserver
- [ ] MW maps hack: scripts/ansible/roles/hitchwiki/tasks/mediawiki.yml:  # TODO: any solution that is cleaner than this temporary dirty hack..
- [ ] explain `ignore_errors: yes`: run `rgrep 'ignore_errors: yes'`and check that every line has a comment with a good explanation
- [-] use [vault](https://docs.ansible.com/ansible/latest/vault.html) for passwords, restructure variable tree as encrypted passwords are not visible to php (maybe db settings for production)

### TLS
- [ ] test TLS config (see [ssl-params.conf](https://github.com/traumschule/hitchwiki/blob/ansible/configs/ssl-params.conf))
- [ ] add [missing HTTP headers](https://securityheaders.io/?q=beta.hitchwiki.org&followRedirects=on) (see [Content Security Policy](https://www.sitepoint.com/improving-web-security-with-the-content-security-policy/))
> Strict-Transport-Security | HTTP Strict Transport Security  is an excellent feature to support on your site and strengthens your  implementation of TLS by getting the User Agent to enforce the use of  HTTPS. Recommended value "strict-transport-security: max-age=31536000;  includeSubDomains".
> Content Security Policy  is an effective measure to protect your site from XSS attacks. By  whitelisting sources of approved content, you can prevent the browser  from loading malicious assets.
> X-XSS-Protection  sets the configuration for the cross-site scripting filter built into  most browsers. Recommended value "X-XSS-Protection: 1; mode=block".
> Referrer Policy  is a new header that allows a site to control how much information the  browser includes with navigations away from a document and should be set  by all sites.
- [ ] read scripts/ansible/roles/hitchwiki/tasks/tls_selfsigned.yml:# TODO https://www.jeffgeerling.com/blog/2017/self-signed-certificates-ansible-local-testing-nginx
- scripts/ansible/roles/hitchwiki/tasks/tls.yml:# TODO check for release of: Let's Encrypt - apache mod md (We use Certbot which works well, so there currently is no reason to change it.)
  - scripts/ansible/roles/hitchwiki/tasks/tls_md.yml:# TODO untested - "unless it's at least beta-level, we should use just letsencrypt's certbot+cron"
- ~use [ansible's letsencrypt module](https://docs.ansible.com/ansible/latest/letsencrypt_module.html)~ (not needed because we [register via Certbot in one step](https://github.com/traumschule/hitchwiki/blob/ansible/scripts/ansible/roles/hitchwiki/tasks/letsencrypt.yml) and set a cron job to renew)

### Tests
- [ ] run [idempotence](https://travis-ci.org/traumschule/hitchwiki/branches) test on debian and  ubuntu (stable and texting)
- [ ] test our playbook with ansible 2.4.1.2 and 2.5 (trunk)
- [-] test with [MW trunk](https://tools.wmflabs.org/snapshots/#!/mediawiki-core/master) ([install MW from git](https://www.mediawiki.org/wiki/Download_from_Git))
- [-] integrate tests with [AnsibleCheck](https://github.com/AnsibleCheck/ansiblecheck) ([HOWTO](https://hub.docker.com/r/ansiblecheck/ansiblecheck/))
- [-] ~run [docker](https://docs.docker.com) and [travis](https://github.com/travis-ci/travis.rb#installation) locally/on beta ([travis client](https://github.com/travis-ci/travis.rb#readme))~

## Later / low priority
- [ ] figure out why [cached](http://jpmens.net/2015/01/29/caching-facts-in-ansible/) facts are not loaded automatically when stored in `/etc/ansible/facts.d/file.yml`
- we can switch from spyc to symfony (both are already implemented. it's merely a performance decision, see "Load Hitchwiki Config" in [mediawiki.php](https://github.com/traumschule/hitchwiki/blob/ansible/configs/mediawiki.php)), affected files: 
  - mediawiki.php`
  - status.sh
  - hitchwiki/tasks/main.yml
  - system.yml
  - composer.json
  - mw-postgres: discourse needs postgres, to save ram it might be worth to use postgres for MW as well
  - nginx: is nginx an option and what would be the benefits?

### Future OS
- [ ] currently xenial is LTS stable, to change later, uncomment other versions in .travis on a new branch and check if they [build with travis](https://travis-ci.org/traumschule/hitchwiki/branches)
- [ ] check why `php-apcu` is not in ubuntu artful
- use [package module](https://docs.ansible.com/ansible/latest/package_module.html) if we deploy to non-debian derived systems (probably won't happen)

**Comment by guaka** [comment]
see #186
