### ISSUE TITLE
setup letsencrypt on hitchwiki.org

### ISSUE THREAD

**Issue by albjeremias** [Hitchwiki/hitchwiki#175]
yeah... hitchwiki.org is not https yet.

**Comment by platschi** [comment]
That's a matter of five minutes with [certbot](https://certbot.eff.org/). If somebody can give me temporary server access, I'm happy to set it up.

**Comment by kradan** [comment]
It's done now. Thanks!

**Comment by leonhandreke** [comment]
It seems HTTPS is still not the default for hitchwiki.org

**Comment by guaka** [comment]
https works now, including redirect from http://hitchwiki.org to https
