### ISSUE TITLE
beta.hitchwiki.org is broken

### ISSUE THREAD

**Issue by albjeremias** [Hitchwiki/hitchwiki#176]
![image](https://user-images.githubusercontent.com/26681446/41739057-302ee284-7594-11e8-8927-957b0abec03a.png)
`Uncaught Exception: VisualEditor is not compatible with the current MediaWiki core (version 1.29.2)`

**Comment by guaka** [comment]
the beta.hitchwiki.org server is not even up anymore
we may have a new one but at this point I'm closing this issue
