### ISSUE TITLE
Internal error on ListUsers

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#177]
http://hitchwiki.org/en/Special:ListUsers

reported to me by @akronix

<img width="907" alt="image" src="https://user-images.githubusercontent.com/54728/46921399-01e00680-cffb-11e8-8186-f083c571aa9a.png">

**Comment by guaka** [comment]
still bork
`[2a8500fd063b6dc349725e28] 2019-07-18 20:57:25: Fatal exception of type "Wikimedia\Assert\ParameterAssertionException"`

**Comment by tillwenke** [comment]
still present?
