### ISSUE TITLE
Vagrant could not be accesed

### ISSUE THREAD

**Issue by AugustasV** [Hitchwiki/hitchwiki#178]
Tryed to install hitchwiki at my local machine by using vagrant install plugin, but got erro
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:103:in `call': The box 'ubuntu/xenial64' could not be found or (Vagrant::Errors::BoxAddShortNotFound)
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/ubuntu/xenial64"]
Error: Operation timed out after 300315 milliseconds with 0 out of 0 bytes received
The box 'ubuntu/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/ubuntu/xenial64"]
Error: Operation timed out after 300315 milliseconds with 0 out of 0 bytes received

How to fix it?

**Comment by leonhandreke** [comment]
I remember having an issue like this a while ago as well. Are you running on Debian (or something along those lines) by any chance and using the distro-packaged version of Vagrant?

**Comment by AugustasV** [comment]
> I remember having an issue like this a while ago as well. Are you running on Debian (or something along those lines) by any chance and using the distro-packaged version of Vagrant? I think I may have fixed it by installing the current version from their Website.

Thank you! Yes, just downloaded current version form website - that worked!

**Comment by leonhandreke** [comment]
Great, happy to hear that it worked! What are you working on? There is a development Slack channel, would you like to be invited?

**Comment by AugustasV** [comment]
I would like to explore how to make these hitchhiking spots editable again. I found project https://github.com/NoryDev/hitchspots and was thinking maybe it could be possible to make new database, that people could add new spots?
