### ISSUE TITLE
Big project cleanup

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#179]
Thanks to @zrthstr we're doing a project cleanup.

General goals:
1. More robustness: backups, stable server
2. More clarity

Stuff to do:
- [x] What's the status of this code? Is this HW 3.0? #187
- [x] Set up production server through Ansible  #186 
- [ ] Move code from private repo into this (with ansible-vault)
- [ ] Branches?
- [ ] More fixes
- [x] Close old, currently unhelpful issues
- [ ] Archive or delete repos that are unused? e.g. https://github.com/Hitchwiki/
- [ ] _what else? any clutter, unused stuff?_

**Comment by leonhandreke** [comment]
Hey, any updates on this? How far did you get? I am interested in joining this effort to get Hitchwiki to a well-maintainable state again.

**Comment by guaka** [comment]
great!

well the idea was to do a complete overhaul (with docker, which I'm not good at), and then this got stuck (not the first time)

so any improvement has to be an incremental cleanup/improvement, so the results are directly usable
