### ISSUE TITLE
keep spammers out

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#188]
- [x] @simison installed https://www.mediawiki.org/wiki/Extension:AkismetKlik
- [ ] tweak stuff?
- [ ] clean up of settings etc.
- [ ] _add more_

**Comment by simison** [comment]
The spam always hits `User:` endpoints which is interesting. I wonder if we could tighten the checks for those pages only e.g. with additional captcha?

I tried testing Akismet with the username they mention in their docs but that didn't get marked as spam, so I'm suspicious if it's actually working at all.

**Comment by simison** [comment]
You can see some tweaks I did in https://github.com/Hitchwiki/hitchwiki-private/commit/1cbb59f82c79e158c2c58a91a01e740094769199

One theory was that spammers get promoted automatically to `autopatrolled` group and then they get past some protections. You could try to verify that theory by manually testing?

I don't know if that group is useful in anyway and if we should just disable it?

**Comment by guaka** [comment]
cloudflare rules!

no new spammers or spam since about 5 hours

let's keep an eye on these the coming days:
- https://hitchwiki.org/en/Special:Log/newusers
- https://hitchwiki.org/en/Special:RecentChanges

**Comment by guaka** [comment]
lgtm

reopen if/when spam returns
