### ISSUE TITLE
Bug: Images cannot be embedded / Error creating thumbnail

### ISSUE THREAD

**Issue by platschi** [Hitchwiki/hitchwiki#193]
When trying to add a picture on a random hitchwiki page, the following error message appears:

`Error creating thumbnail: Unable to save thumbnail to destination`

A quick search in the [Mediawiki Manual](https://www.mediawiki.org/wiki/Manual:Common_errors_and_symptoms#Unable_to_save_thumbnail_to_destination) throws this out:

> Unable to save thumbnail to destination

> If you get the error "Error generating thumbnail / Error creating thumbnail: Unable to save thumbnail to destination" and the $wgUploadDirectory directory has the correct permissions (at all levels), check that $wgTmpDirectory actually exists. (Unlike some path variables such as $wgCacheDirectory, $wgTmpDirectory is not created at runtime.) A more detailed error message may be available if you turn on logging with $wgDebugLogFile.

Only somebody with server access can fix this. Either permissions are set wrong or the directories are not set correctly. Would be great to do so we can clean up hitchwiki a bit :)

**Comment by tillwenke** [comment]
still present?
