### ISSUE TITLE
[Security] High Security Alert: Grunt Dependency

### ISSUE THREAD

**Issue by platschi** [Hitchwiki/hitchwiki#194]
Since a week I'm receiving high security alert emails asking us to update ``grunt`` to ``~>1.3.0``

I'll add a pull request to fix this but I have no idea if the update will break anything, so please somebody with the proper knowledge double check and if all is good, merge.

// EDIT

Nevermind, it's for an archived repository ``/mediawiki-extensions-VectorBeta/``, so whatever. Would still be great to stop those daily email digests somehow.

**Comment by simison** [comment]
It's fine, Grunt is a local dev tool anyway and not a public-facing code. It's also in an un-needed repo, which is even a fork originally... so yeah no concerns just to ignore those. :-)

Thanks for caring tho! :-)

**Comment by simison** [comment]
> Would still be great to stop those daily email digests somehow.

Hm, Github's bot is disabled for archived repos — is it Github sending you those alerts or something else? Might be worth writing to github about it.
 
<img width="997" alt="image" src="https://user-images.githubusercontent.com/87168/119467204-f83fe300-bd4d-11eb-94d3-c47661514f10.png">
