### ISSUE TITLE
Broken gas station map at German wiki

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#46]
> looking for the gas station map and.. the link says the pic has been deleted
> could u maybe do something about it when u have some time?
> or maybe just write that need to be fixed..?
> the broken link is in the map section, in this phrase: 
> " For a good map to print out and bring with you that has all the service stations on it have a look here: Rastekarte. "

I guess it's this what was there before: http://www.autobahnatlas-online.de/AutobahnkarteMitAS.pdf

**Comment by robfir** [comment]
http://i.imgur.com/9qhxvxJ.jpg/
http://www.autobahnatlas-online.de/AutobahnkarteMitAS.pdf

**Comment by leonhandreke** [comment]
http://i.imgur.com/9qhxvxJ.jpg/ is a bit broken. See the Autobahn west of Kassel, which seemingly ends nowhere but is actually continued a centimeter above.

**Comment by zrthstr** [comment]
no progress
