### ISSUE TITLE
install Parsoid

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#50]
install [Parsoid](https://www.mediawiki.org/wiki/Parsoid)
so we can have a [zim version of hitchwiki](https://sourceforge.net/p/kiwix/feature-requests/597/), for [kiwix](http://kiwix.org)

and if we have that we might as well do [VisualEditor](https://www.mediawiki.org/wiki/VisualEditor) as well.

@simison @MrTweek

**Comment by simison** [comment]
Parsoid is now installed at dev, will go to production ~mid Feb.

@kelson42 should I setup something else for this?

**Comment by kelson42** [comment]
Great! Looks good to me. It's important that the Parsoid API (and the Mediawiki API) is public, otherwise you will need to build the ZIM files (offline version) on your server.

**Comment by simison** [comment]
Great, they're public. I'll ping you again when it's online!

@MrTweek we'll need to install NodeJS to production in a few weeks time.

**Comment by kelson42** [comment]
Any news on this? Do you need help?

**Comment by guaka** [comment]
@kelson42 do you have experience with ansible? I'd like to set up the new server through ansible.

**Comment by kelson42** [comment]
No experience with ansible.

**Comment by zilverdistel** [comment]
Is there anything happening on this? I would be really happy to take a zim on my next travel...

**Comment by ashecorven** [comment]
Anything happening with this?

**Comment by kelson42** [comment]
Just wanted to let know that the Kiwix team is still interested to provide offlien versions of Hitchwiki https://twitter.com/KiwixOffline/status/682160149797171200

**Comment by nemobis** [comment]
Recently a docker package was released, which includes Parsoid and on top of which you might find easier to add your configurations: https://lists.wikimedia.org/pipermail/wikitech-l/2015-December/084394.html

**Comment by omelnyk** [comment]
We got it already rolling on beta.hitchwiki.org, but we shouldn't use it for ZIM/Kiwix purpose until:
- beta has been thoroughly tested;
- latest database+images dumps are imported into it;
- it completely replaces the old Hitchwiki.

**Comment by zrthstr** [comment]
no progress
