### ISSUE TITLE
EPUB / PDF export

### ISSUE THREAD

**Issue by matyasbach** [Hitchwiki/hitchwiki#51]
Pioja posted this at hitchwiki discussion: "It would be great if there would be an option to compile the hitchwiki to an EPUB ebook format. I downloaded parts of the site and compiled a manual epub for the countries/cities of my interest. It helped me greatly when being stuck in the boonies without wi-fi.

Automatic examples like this can be seen in the wikipedia. I could try and write up a website crawler and compile that book, but it makes more sense to have that piece of software within the wiki site. Moreover, I will be on the road until the end of this year, so most likely nothing can happen until then from my side."

And personally I'd like it a lot too. Maybe pdf export as well?

**Comment by simison** [comment]
Going to add https://www.mediawiki.org/wiki/Extension:Collection to new Hitchwiki (it's the same what Wikipedia uses)

**Comment by zrthstr** [comment]
no progress. modern browsers can pdf export..
