### ISSUE TITLE
Update old Hitchwiki articles into new format

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#59]
Geocode location for
- [x] Cities
- [x] Roads
- [x] Countries
- [x] Airports
- [x] Border crossings
- [x] Continents
- [x] Regions
- [x] Islands

Writing stuff to Hitchwiki; https://www.mediawiki.org/wiki/Manual:Pywikibot
- [x] Turn old articles into SMW templates (city, country)
- [x] Semantically connect city articles to country articles
- [x] Turn Places from old  [maps](http://hitchwiki.org/maps/) to new "Spot" semantic articles
- [x] Connect Spots to nearby city/airports/islands/border crossing articles

We're still thinking what will be the final format of everything tho.

We'll probably use fixed zoom levels. Bounding box is nice, but has quite some issues sometimes (eg. France or Netherlands).

**Comment by simison** [comment]
Progress so far:
https://dl.dropboxusercontent.com/u/30369146/HitchWiki-Articles-Geocode.txt

**Comment by willish** [comment]
I'd be keen to have a stab at this

**Comment by simison** [comment]
http://hitchwiki.org/en/Hitchwiki:Database_dumps

**Comment by simison** [comment]
#69
