### ISSUE TITLE
Personal bar invisible. Login/create account links hidden

### ISSUE THREAD

**Issue by willish** [Hitchwiki/hitchwiki#64]
This seems due to the compact personal bar. When I change to '0' it seems to work

    $wgDefaultUserOptions['betafeatures-vector-compact-personal-bar'] = '1';

**Comment by simison** [comment]
Ahh, yess.

So, we want that feature only for logged in users I guess. That's a feature for https://github.com/simison/BetaFeatureEverywhere

**Comment by simison** [comment]
Fixed with https://github.com/simison/BetaFeatureEverywhere/pull/1
