### ISSUE TITLE
Install new reCaptcha

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#66]
Let’s give this a try; 

https://github.com/vedmaka/Mediawiki-reCaptcha
https://www.mediawiki.org/wiki/Extension:ReCaptcha

Right away or test first at Nomadwiki/Trashwiki?

**Comment by guaka** [comment]
Last time I tried recaptcha it didn't really work...

**Comment by simison** [comment]
So just to make difference —

Old reCaptcha (now at Hitchwiki, leaky):
![image](https://cloud.githubusercontent.com/assets/87168/5606367/9a953622-9434-11e4-850c-b9902c3de1fb.png)

New reCaptcha:
![image](https://cloud.githubusercontent.com/assets/87168/5606371/af9af660-9434-11e4-94df-ec51f8332c45.png)

Read more: http://www.google.com/recaptcha

It's Google but seems to be the strongest out there for now, so I'd use it for pragmatic reasons.

**Comment by guaka** [comment]
Ah, ok it's "NEW and IMPROVE:D"
Yeah let's try this.
I'll set it up on wiki.yt one of these days, it's been a long time without
proper signups there...

**Comment by simison** [comment]
Ye the video is quite cheesy. :-) So let's see what happens with it on wiki.yt for a few days and add it to HW as well.

**Comment by guaka** [comment]
https://github.com/vedmaka/Mediawiki-reCaptcha/issues/3

**Comment by guaka** [comment]
new recaptcha is working pretty well on wiki.yt

looks like hitchwiki has old recaptcha

![screen shot 2015-01-08 at 00 43 58](https://cloud.githubusercontent.com/assets/54728/5655547/7e06ab56-96cf-11e4-918f-fb14c64bc91a.png)

**Comment by simison** [comment]
@guaka looks good on wiki.yt? I'll add this to old/new HW then.

**Comment by guaka** [comment]
Looks fine on http://wikiytchanges.meteor.com/ so yeah, add it to HW

**Comment by simison** [comment]
Enabled this at Hitchwiki.

http://hitchwiki.org/en/index.php?title=Special:UserLogin&returnto=Special%3AUserLogin&type=signup

@prino could you hold on blocking people again? This extension seems to be working well for Nomadwiki & Trashwiki.

**Comment by prino** [comment]
Why don't we simply forward the requests to open an account to a number of people, I'm happy to volunteer as one of them, with the chosen username, email address and IP address and then let these volunteers enable the opening of the account? 

Or completely block any account being created from a gmail email address, of the 38 spams that were posted just today to my blog, 35 came from bogus gmail accounts?

Or completely block IP ranges. On FanDeZhi ( http://zos.efglobe.com/index.php ) which I administer 111.*.*.*, 112.*.*.* and 113.*.*.* (yes, nearly 50 million IP addresses, all mostly China) are completely blocked. Sledgehammer vs nut, but it works.

Autoblock usernames that are not used within 24/48/72 hours from being opened?

And finally, install a link to http://www.stopforumspam.com/ to do most of the checking and a way to let admins transfer the info of manually blocked accounts to them!
Block any username that contains both an "x" *and* a "q", any username where the "q" is not followed by a "u", any username with embedded digits (User34name), any username ending on digits?

**Comment by simison** [comment]
Usernames with "x" or using "gmail emails" and whatnot are too fuzzy, no way.

Just don't block anyone and don't start blocking anyone without consulting here first, let's see how this extensions holds up. So far it has done a good job at other wikis hosted by @guaka .

**Comment by guaka** [comment]
See also http://wikiytchanges.meteor.com/

**Comment by prino** [comment]
Not just "x", but "x" ***AND*** "q"...

**Comment by Remigr** [comment]
Maybe I am stupid, but how can this make sense ??

**Comment by simison** [comment]
@prino I can see you're still blocking people. http://hitchwiki.org/en/Special:BlockList

Please stop it will ya?

**Comment by prino** [comment]
I've not blocked anyone today, although four of the five new users are quite likely bogus, .e.g Matteoporman is a typical Iranian name...

**Comment by prino** [comment]
My not entirely wild guess? It's already gone the way of the dodo... :(

**Comment by simison** [comment]
I'm looking into hardening this, testing a few options at our new dev-setup first.

Eg. http://thingelstad.com/updated-dynamic-questy-captchas/
