### ISSUE TITLE
Hitchwiki Newsletter Feb 2015

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#67]
- collect all emails from Hitchwiki users
- send out one newsletter at end of Turkey time
## first newsletter
- **you can unsubscribe to this newsletter**
- check out these improvements: on wiki, maps, android app, etc. (several paragraphs)
- you can help: contribute to hitchwiki, contribute with code, bugs etc. on github
- check out trustroots

cc @simison

**Comment by simison** [comment]
:+1: I'll take care of this in a month around early Feb.

**Comment by traumschule** [comment]
i would like to help writing it to give the community an update where the development stands and what kind of help is needed, started with http://hitchwiki.org/en/Category:Tech_team
