### ISSUE TITLE
Migrating old contents

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#69]
We'll need to migrate current wiki articles into a new format (semantic stuff) and merge hitchwiki maps into the wiki.
- [x] Generate coordinate for each geolocation at the current wiki: countries, cities, airport, border crossings, highways, etc...
- [x] Go trough all the city and country articles and wrap them into semantic wiki stuff
- [x] Add semantic links between articles: connect cities to countries
- [x] Import from old maps SQL all spots into separate articles
- [x] Import from old maps SQL all ratings, waiting times and comments into new DB either directly via SQL _or_ via the API
- [x] Semantic-connect spots articles from # km diameter to city articles
- [ ] Clean out `<map lat='48.83398957668602' lng='2.34283447265625' zoom='10' view='0' float='right'/>` tags
- [ ] Clean out `{{legend}}`
- [ ] Parse Infobox templates:
  Currently this stuff resides in [Template:Infobox_Country](http://hitchwiki.org/en/Template:Infobox_Country):

```
{{Infobox Country
|in = 
|map =
|language = 
|capital = 
|pop = 
|currency = 
|hitch = 
|hitchbase = 
|avp = 
|links =
|paved = 
|BW =
}}
```

And this stuff in [Template:Infobox_Location](http://hitchwiki.org/en/Template:Infobox_Location):

```
{{Infobox Location
|name = 
|name_native = 
|symbol = 
|country = 
|state = 
|state_symbol = 
|subdivision_type = 
|subdivision_name = 
|subdivision_symbol = 
|region = 
|region_symbol = 
|subdivision2_type = 
|subdivision2_name = 
|subdivision2_symbol = 
|map = 
|pop = 
|plate = 
|roads = 
|hitchbase = 
|links = 
}}
```

...most of it we can get for Geonames anyway, though.

**Comment by guaka** [comment]
Which old contents? :)

**Comment by simison** [comment]
Hah, you were fast. @omelnyk just wanted to have a issue number for his script commits. I'll write down what needs to be done, just a mo.

**Comment by omelnyk** [comment]
https://gist.github.com/anonymous/478d83dddd6c780e9e34
Latest version. At this point every bug becomes a feature ;)

**Comment by omelnyk** [comment]
Necessary article migration script improvements for each processed article:
- [ ] move text from the top of the article to _Description_ field of the Semantic template 
- [ ] fetch _population_ and _adminName1_ from Geodata
- [ ] extract _plate_ and _roads_ from old Infobox template
- [ ] move links from old Infobox template to the bottom of article
- [ ] remove all location-related Infobox templates from the article

**Comment by omelnyk** [comment]
Ideas to keep bot fail-proof:
- [ ] print out diff of article content upon saving
- [ ] save changes in several goes (add SMW template, remove Infoboxes and <map ../>, ..)
- [ ] keep list of articles that have been migrated in a database table (similar to spotmigrate)

**Comment by omelnyk** [comment]
Idea: possibly use OrderedDict to preserve logical order of the fields in the generated templates.

**Comment by omelnyk** [comment]
Spot migration necessary improvements:
- [ ] need to set _Country_ for each migrated spot (not trivial as our country names sometimes differ from Geodata's)

**Comment by simison** [comment]
>not trivial as our country names sometimes differ from Geodata's

Perhaps that iso-code added to countries would help at that point, though?

**Comment by omelnyk** [comment]
To do (based on on last night's beta deployment issues):
- [ ] avoid country (and partially city) Geonames lookup throttling
- [ ] parse infoboxes (227 of them) with nested templates

**Comment by omelnyk** [comment]
- [ ] `Czechia` --> `Czech Republic`

**Comment by omelnyk** [comment]
aka "the neverending task" :)

**Comment by simison** [comment]
> remove tables created by extensions we don't use anymore

We can do this manually.
