### ISSUE TITLE
while trying Vagrant: missing VisualEditor.php 

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#70]
Didn't see any errors while installing stuff.
Also ran `sh pull-hw-extensions.sh`.
Still getting this at http://hitchwiki.dev/en/
```
Warning: require_once(/var/www/public/wiki/extensions/VisualEditor/VisualEditor.php): failed 
to open stream: No such file or directory in /var/www/configs/mediawiki.php on line 264
```

cc @simison

**Comment by simison** [comment]
Yep, I was adding VE just last night and still some stuff seems to be broken. I'm working on install script now so you can try again in a couple of hours.

**Comment by simison** [comment]
Aight, all fixed now, just tested to do a fresh install.

You can [test VisualEditor also](http://hitchwiki.dev/en/Main_Page?veaction=edit) It sometimes gives an error `Uncaught Error: Unknown dependency: schema..Edit` — no idea why.
