### ISSUE TITLE
Create a smart template for road signs

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#73]
Create a smart template that figures from semantic road data which figures out to which country road belongs to etc.

Ask here for details / I can elaborate this more later.

**Comment by Kundrt** [comment]
I'd like to do that. I have lot of ideas with roads/roads signs too and hopefully soon I'll have a place to live :D (+internet).

**Comment by simison** [comment]
Great! I had you in mind already for this stuff. :-) We can have a chat to figure out best options. We'll have in a day or two this stuff working on demo server, so you could build new templates there.

If you need a place to work on this, I can host you in Vilnius for 2-6 weeks this spring.

The idea was that new stuff would go online some time in March, so there's plenty of time to get this done.
