### ISSUE TITLE
Edit dropdown button

### ISSUE THREAD

**Issue by Remigr** [Hitchwiki/hitchwiki#75]
- [x] Make the dropdown work properly, now it's tricky to click on it without making it disappear.
- [x] Use edit with visual editor as a default button, and "edit with form" and "edit source" in dropdown.

**Comment by simison** [comment]
#100

**Comment by simison** [comment]
Visual Editor is now default with this change: https://github.com/Hitchwiki/mediawiki-extensions-VectorBeta/commit/a064b47f1a39b5c8efb84bdb6fd679dbfe01e87a
