### ISSUE TITLE
Redirect old maps urls

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#76]
For instance:
http://hitchwiki.org/maps/?place=11616
http://hitchwiki.org/maps/?lat=52.5&lon=13.4&zoom=9
http://hitchwiki.org/maps/?q=Athens
http://hitchwiki.org/maps/?q=50.0098506394,20.0089627504

Make sure old maps API urls still remain working:
http://hitchwiki.org/maps/api/?ping

**Comment by simison** [comment]
?place=123 relates to this: https://github.com/Hitchwiki/HWMap-extension/commit/1d4a742229be8f7970dd7ac343d29f3f37248735

**Comment by traumschule** [comment]
are these working on beta?

**Comment by simison** [comment]
Nope, but it's not very high priority.
