### ISSUE TITLE
Create a Hitchability world map

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#77]
- [ ] a map of world where different countries are coloured by their avg hitchability
- [ ] possibility to rate any country quickly and directly from this page.

Old one: http://hitchwiki.org/en/Hitchwiki:Hitchability

@Remigr I'm sure you'd like this task? :-)

**Comment by simison** [comment]
@Simsadz has some JS+SVG code written for this actually already and the list could be just manually produced table with rating widget next to it.

**Comment by Remigr** [comment]
Done. See https://github.com/Hitchwiki/HWRatings-extension, and https://github.com/Hitchwiki/jvectormap-world-hitchwiki-custom for our world map.
