### ISSUE TITLE
Setup BotBot for #hitchhiking

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#79]
hitchhiking IRC channel could have this fun tool: https://botbot.me/

**Comment by platschi** [comment]
Problem is there's no channel op for #hitchhiking. we had that problem earlier... :(

**Comment by simison** [comment]
Well, we actually have multiple small projects using the same channel, so perhaps they'd understand we'd like to keep the name?

Hitchwiki, Hitchlog, Hitchgathering, Trashwiki, Nomadwiki...

Thanks for checking!

**Comment by platschi** [comment]
Ok, I'll send them an email next days to have a look what we can do.

**Comment by simison** [comment]
Cool, thanks! No hurry.

**Comment by platschi** [comment]
Never received an answer. Trying now to set up https://hubot.github.com/ , also seems promising :)

**Comment by simison** [comment]
Cool, see also #88 chat

**Comment by platschi** [comment]
@traumschule managed to get op and set up hwbot, so we can finally close this issue :+1:
