### ISSUE TITLE
Preserve spot author id during migration

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#81]
When spots are migrated from the old custom tables into the new Hitchwiki, each spot becomes a proper wiki article. All such articles are submitted during migration using pywikibot, hence their author is Hitchbot and edit time is the current timestamp.

Would be nice to restore the original timestamp of the spot, and its author. Could be done either using SQL or a MediaWiki extension.

Relevant:
http://www.mediawiki.org/wiki/Manual:Database_layout
http://www.mediawiki.org/wiki/Extension:ChangeAuthor (does it have an API?)

**Comment by simison** [comment]
Absolutely, would be cool!

Not a show stopper, tho.
