### ISSUE TITLE
WSOD

### ISSUE THREAD

**Issue by robokow** [Hitchwiki/hitchwiki#86]
main page is currently not redirecting anywhere.

**Comment by guaka** [comment]
ping @simison, @mrtweek

I'm taking a quick look now

**Comment by guaka** [comment]
added index.html

can test the fancy front page with symlink: http://hitchwiki.org/indextest.php

**Comment by guaka** [comment]
the problem is probably with .htaccess and WordPress

**Comment by simison** [comment]
Now hitchgathering.org started pointing there, too.

Actually since I disconnected the wiki and the Wordpress installations, these could be separated into different folders. (/var/www/hitchwiki.org and /var/www/hitchgathering.org). 

I can handle.

**Comment by simison** [comment]
@guaka where's that quickfix front page coming from? I'd like to get hitchwiki.org point to /var/www/hitchwiki.org/htdocs/index.php

**Comment by guaka** [comment]
> I can’t give you hitchwiki.org/username/ URLs anymore, sadly.

We can easily 301 redirect them elsewhere though so existing links remain working

**Comment by guaka** [comment]
I just created index.html, which overrides index.php

**Comment by simison** [comment]
I moved languages to http://hitchwiki.org/en/Main_Page and from index.php I'm just:
```php
header("Location: http://hitchwiki.org/en/Main_Page");
die();
```

**Comment by guaka** [comment]
it's a 301 redirect now, fine as well

I think it's better to move the languages up a bit
