### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#88]
We now have [IRC webclient](http://hitchwiki.org/chat/) pointing to #hitchhiking channel (also [via FB](https://www.facebook.com/Hitchwiki/app_145526732257071)) but it's very quiet, except for occasional people saying hi and disappearing in a minute or so.

I'd like to get chat active if it can be done with small effort.

[Slack](https://slack.com/) communities are much more approachable for non-geeks due it saves history and friendly interface. Some examples: https://github.com/filipelinhares/awesome-slack and http://hashtagnomads.com/

I wouldn't like to rely on Slack due it might just cause costs in the future and would be great to integrate this into IRC ([although...](https://github.com/ekmartin/slack-irc), [as well](https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP)), but I'm not sure what options are out there. I'll do more research at some point this summer.

http://alternativeto.net/software/slack/?license=free

---

@jancborchardt did you guys have some comparisons written down with #opensourcedesign dudes? @pierreozoux might have some knowledge on this as well.

**Comment by jancborchardt** [comment]
We’re trying to build a Slack-like alternative based on IRC with [Shout](https://shout-irc.com) plus [Slick](https://github.com/opensourcedesign/slick). In the works, and any help is appreciated. :)

There’s also slack-irc cross-posting gateways. But yeah, especially _us_ should really try and work on making an alternative real.

**Comment by pierreozoux** [comment]
I can host this this week if you want: https://github.com/RocketChat/Rocket.Chat
(Based on meteor)

(There is also this one: http://spacetalkapp.com/, based on meteor also, but less stars on GitHub)

Let me know :)

**Comment by simison** [comment]
https://sdelements.github.io/lets-chat/ seem very popular.

**Comment by pierreozoux** [comment]
You can test rocket.chat here if you need: https://chat.tokoloho.co/room/57om6EQCcFami9wuT

Let's chat looks cool also!

**Comment by simison** [comment]
I'm sorta missing a way to connect chat to existing IRC channel at Freenode (#hitchhiking).

**Comment by pierreozoux** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/216
https://github.com/sdelements/lets-chat/issues/246

Yep, it's coming!

**Comment by simison** [comment]
Nice!

So the bottom line is; which community/software ends up having stable IRC support sooner. I wouldn't mind implementing this before proper IRC support, if I can promise everyone it's on the way.

Let's chat has some sort of XMPP support, which also is a huge plus.

**Comment by pierreozoux** [comment]
Let me know if you wan an instance of rocket.chat, this is already implemented for IndieHosters :)

**Comment by PerfectCarl** [comment]
You can also find ideas there: http://softwarerecs.stackexchange.com/questions/18754/alternatives-to-slack-for-team-communication

**Comment by pierreozoux** [comment]
@PerfectCarl thanks for the pointer!
