### ISSUE TITLE
Update LinkedIn picture

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#89]
There's a logo from 2009 there. :-D

https://www.linkedin.com/company/1043916 (somehow via this page it just shows gray, but old logo is visible at profiles).

It could also be marked with "non-profit" category.

Here's the latest version:
![hitchwiki-logo](https://cloud.githubusercontent.com/assets/87168/8822136/e6802550-306b-11e5-878f-8f0f3d8957db.png)

**Comment by guaka** [comment]
done at last :)
