### ISSUE TITLE
Preferences broken

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#91]
"A database query error has occurred. This may indicate a bug in the software."

![screen shot 2015-09-16 at 21 34 28](https://cloud.githubusercontent.com/assets/54728/9916043/c3793a4e-5cba-11e5-93e4-79664638de46.png)

**Comment by guaka** [comment]
@simison @omelnyk do you have a dev setup of Hitchwiki somewhere that I can play around with? I was thinking of fixing this but I can only really do it on the live server, which is a bad idea...

**Comment by simison** [comment]
Nope, sorry.

**Comment by guaka** [comment]
Just encountered the same error message on http://veganwiki.info/de, after setting up basics. Solution there was to go to Special:SMWAdmin and install SMW stuff. For hitchwiki it may just be a matter of running maintenance/update.php

**Comment by guaka** [comment]
[Asked the question](http://stackoverflow.com/q/32630094/1245190) and answered it myself.

**Comment by guaka** [comment]
Fixed by disabling OAuth. I hope this doesn't break anything else? @simison

**Comment by simison** [comment]
I don't think nothing was using it atm. Someone was planning but never got back to it.
