### ISSUE TITLE
  No images and no maps in Russian Hitchwiki

### ISSUE THREAD

**Issue by ale-xy** [Hitchwiki/hitchwiki#93]
Images in Russian Hitchwiki are missing (e.g on [Main Page](http://hitchwiki.org/ru/%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0) ).
Maps in the articles are also missing despite pages have map tags.

**Comment by platschi** [comment]
The image issue seems to be wiki-wide.  @simison @guaka you're on it? Anything that can be done to help with it?

**Comment by ale-xy** [comment]
Seems that some images are missing in all languages, but some are available in English, but unaccessible in Russian (Am I right assuming [[File:]] links are independent on language sections?)

**Comment by guaka** [comment]
Sorry I really don't have time for Hitchwiki anymore these days, nevertheless, I'm confident the next gen will work out how to get things done and to help a bit with that I'm happy to find 30 minutes to help someone get started.

**Comment by MrTweek** [comment]
I just fixed the images on all wikis. Let me know if you still find any missing ones.

**Comment by ale-xy** [comment]
For Russian section, images from Wikimedia Commons (country flags) work, but other images visible in English HW don't. 
Example: (Asia article)
http://hitchwiki.org/ru/%D0%90%D0%B7%D0%B8%D1%8F / http://hitchwiki.org/en/Asia

**Comment by ale-xy** [comment]
Example of article with map:
http://hitchwiki.org/ru/%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3

**Comment by traumschule** [comment]
> @ale-xy: Do you have an example of a page with a broken map? I can't find any right now.
Our [profile page](http://hitchwiki.org/en/User:Traumschule#How_to_get_there) should show a map but doesn't. Probably you know [this issue](http://hitchwiki.org/en/index.php?title=Hitchwiki_talk:Maps&diff=prev&oldid=88956) already.
