### ISSUE TITLE
Slow for some users

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#94]
From the mailing list:

> I can confirm that I have similar issues of Hitchwiki loading delays (specifically, in Russian section). >Sometimes everything is fine, but sometimes loading a page takes about a minute.
> I'm in Israel, it couldn't be local troubles of Ravil.
> Probably this started after recent server update?

**Comment by simison** [comment]
@MrTweek perhaps check the name servers?

**Comment by MrTweek** [comment]
I can somewhat reproduce this. Some pages are slow, but most are pretty quick.
If a page is slow, reloading it again it pretty fast. Maybe a caching issue?

**Comment by simison** [comment]
I just observed the same with Russian wiki and thought of writing here that it could be cache issue. :-)
