### ISSUE TITLE
CAPTCHA broken

### ISSUE THREAD

**Issue by sitarane** [Hitchwiki/hitchwiki#95]
Hi, I just firefox-on-ubuntu-64-tested that when you create an account, the account-creation page does not present a captcha to the user. When the user has filled in all the fields and hits "send", the page informs him that the captcha is wrong.

*I know about this because we have a backlog of messages telling us just that on the hitchwiki facebook page, first one dating back to one month ago. Oh the shame...*

**Comment by simison** [comment]
Hum, I thought @MrTweek fixed this just two days ago.

**Comment by sitarane** [comment]
Someone wrote again to the FB page, and I went ahead and checked, and the account creation still fails, but in a different way.

Now I can see the captcha. I click the box, it gives me a green tick, everything is ready for the "register" button so I click it. The page refreshes back to the same one, with an additional red error message: "Please solve the captcha" (I had).

**Comment by simison** [comment]
Fixed again finally after second attempt. There were two of these plugins and they were messing up each other.

**Comment by sitarane** [comment]
Test succesful. Sorry, I didn't know you can't delete a user. Test account "sexy69" with email sitaranetest@mailinator.com can be nuked with no consequence. My bad.

**Comment by simison** [comment]
Hehe, no probelmo. I also made some fake account for testing. It's just some bits. Thanks for testing tho.

(@prino might take care of them)
