### ISSUE TITLE
Rename page checkboxes (”keep redirect” and “start watching”) not working

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#98]
>started to rename articles of recently renamed cities in Ukraine, on Rename page checkboxes do not work (Chrome, MacOS X)

https://hitchwiki.slack.com/archives/general/p1480256303000003

**Comment by ale-xy** [comment]
Tired to rename page without touching the checkboxes. Checkboxes looked like they are not checked, but redirect was created.
Seems that the checkboxes are working, but ticks are not displayed.
